# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapKitTutorial' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 3.2.0'

  # Pods for SnapKitTutorial

  target 'SnapKitTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SnapKitTutorialUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
